# Generated by Django 4.1.2 on 2022-10-05 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketDataInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=1)),
                ('series', models.CharField(max_length=2)),
                ('security', models.CharField(max_length=200)),
                ('prev_cl_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('high_52_wk', models.DecimalField(decimal_places=2, max_digits=7)),
                ('low_52_wk', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ind_sec', models.CharField(max_length=1)),
                ('corp_ind', models.CharField(blank=True, max_length=5, null=True)),
                ('trades', models.IntegerField()),
                ('net_tradeval', models.CharField(max_length=15)),
                ('net_tradeqty', models.CharField(max_length=15)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.details')),
            ],
        ),
    ]
