# Generated by Django 4.1.2 on 2022-10-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketdatainfo',
            name='ind_sec',
            field=models.CharField(max_length=5),
        ),
    ]
