# Generated by Django 4.1.2 on 2022-10-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('series', models.CharField(max_length=2)),
                ('listing_date', models.CharField(max_length=50)),
                ('paid_up_value', models.IntegerField()),
                ('market_lot', models.IntegerField(default=1)),
                ('isin_number', models.CharField(max_length=15)),
                ('face_value', models.IntegerField()),
                ('symbol', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
            ],
        ),
    ]
